# Generated by Django 4.0.6 on 2023-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filetype',
            field=models.CharField(choices=[('pdf', 'pdf'), ('jpeg', 'jpeg'), ('mp3', 'mp3'), ('mp4', 'mp4'), ('docx', 'docx')], max_length=10),
        ),
    ]
